### ISSUE TITLE
Scout moves really slowly

### ISSUE THREAD

**Issue by VanillaCold** [VanillaCold/Spore-ImprovedHologramScout#1]
unlike in other stages, it seems to completely ignore its speed and instead, it just moves at what would be speed 1 in the Creature Stage.

**Comment by VanillaCold** [comment]
This is just due to the larger size of the creature. Shrinking it down makes you faster again.

**Comment by DarianLStephens** [comment]
Question is, does its speed actually change, or is it an illusion where it stays the same, but the different size makes it appear to be moving faster or slower?
